package com.jpagdi.cromascheduler.data.repository

import androidx.room.withTransaction
import com.jpagdi.cromascheduler.data.db.CromaDatabase
import com.jpagdi.cromascheduler.data.entity.AvailabilityEntityType
import com.jpagdi.cromascheduler.data.entity.ConflictRecordEntity
import com.jpagdi.cromascheduler.data.entity.PeriodBlock
import com.jpagdi.cromascheduler.data.entity.ScheduleAssignmentEntity
import com.jpagdi.cromascheduler.data.entity.ScheduleRunEntity
import com.jpagdi.cromascheduler.data.entity.SessionEntity
import com.jpagdi.cromascheduler.data.entity.SessionTypeEntity
import com.jpagdi.cromascheduler.data.export.ScheduleExportRow
import com.jpagdi.cromascheduler.data.timeslot.TimeslotGenerator
import com.jpagdi.cromascheduler.data.timeslot.TimeslotInfo
import com.jpagdi.cromascheduler.engine.SchedulingEngine
import com.jpagdi.cromascheduler.engine.SchedulingInput
import com.jpagdi.cromascheduler.engine.coloring.ColoringAlgorithmRegistry
import com.jpagdi.cromascheduler.engine.model.Timeslot
import com.jpagdi.cromascheduler.engine.optimize.OptimizationResult
import com.jpagdi.cromascheduler.engine.optimize.ScheduleOptimizer
import com.jpagdi.cromascheduler.engine.repair.RepairEngine
import com.jpagdi.cromascheduler.engine.repair.RepairResult
import com.jpagdi.cromascheduler.engine.rooms.EngineRoom
import com.jpagdi.cromascheduler.engine.validation.ConstraintValidator
import com.jpagdi.cromascheduler.engine.validation.ConstraintViolation
import com.jpagdi.cromascheduler.engine.validation.ValidationContext
import java.util.UUID

object ScheduleMode {
    const val GENERATE = "GENERATE"
    const val GENERATE_EXAM = "GENERATE_EXAM"
    const val REPAIR = "REPAIR"
    const val OPTIMIZE = "OPTIMIZE"
    const val IMPORTED = "IMPORTED" // an existing schedule uploaded for the standalone Repair feature, not generated by the engine
}

/**
 * The single place that assembles a SchedulingInput from whatever's currently in
 * Room and turns engine output back into persisted rows. Every "mode" the spec
 * lists (Generate / Generate Exam / Validate / Repair / Optimize) goes through the
 * SAME underlying engine calls — the only thing that differs between them is which
 * sessions get selected and which engine entry point gets called.
 */
class ScheduleRepository(private val database: CromaDatabase) {

    /** [timeslots] is always supplied by the caller now — see [timeslotsFor], the one place that decides which run's period blocks apply. There's no global fallback here on purpose: a caller that forgets to pass real timeslots gets an empty, clearly-broken result, not a silently-wrong one borrowed from some other run. */
    suspend fun buildSchedulingInput(timeslots: List<TimeslotInfo>, sessionFilter: (SessionEntity) -> Boolean = { true }): SchedulingInput {
        val teachers = database.teacherDao().getAll()
        val rooms = database.roomDao().getAll()
        val sections = database.sectionDao().getAll()
        val sessions = database.sessionDao().getAll().filter(sessionFilter)

        val engineSessions = sessions.toEngineSessions()
        val engineRooms = rooms.map { EngineRoom(it.id, it.capacity, it.type) }
        val sectionCounts = sections.associate { it.id to it.studentCount }

        val blockedTeacher = teachers.associate { teacher ->
            teacher.id to database.availabilityDao()
                .getBlocksFor(AvailabilityEntityType.TEACHER, teacher.id)
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }
                .toSet()
        }
        val blockedRoom = rooms.associate { room ->
            room.id to database.availabilityDao()
                .getBlocksFor(AvailabilityEntityType.ROOM, room.id)
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }
                .toSet()
        }

        val allTimeslots = timeslots.map { Timeslot(it.dayOfWeek, it.periodIndex) }
        val definedPeriodsByDay = timeslots.groupBy { it.dayOfWeek }.mapValues { (_, v) -> v.map { it.periodIndex }.toSet() }

        val availableBySession = engineSessions.associate { session ->
            val blocked = session.teacherId?.let { blockedTeacher[it] }.orEmpty()
            session.id to allTimeslots.filter { it !in blocked }
        }

        return SchedulingInput(
            sessions = engineSessions,
            availableTimeslotsBySession = availableBySession,
            rooms = engineRooms,
            sectionStudentCounts = sectionCounts,
            blockedTeacherSlots = blockedTeacher,
            blockedRoomSlots = blockedRoom,
            definedPeriodsByDay = definedPeriodsByDay,
        )
    }

    /**
     * Decodes a run's OWN stored period blocks/days and regenerates its timeslot grid on the
     * spot — this is what replaced reading one shared global `timeslots` table. A run created
     * before periodBlocksEncoded/activeDaysEncoded existed (empty strings) falls back to a
     * generic default rather than producing zero timeslots and silently unresolving everything.
     */
    private fun timeslotsFor(run: ScheduleRunEntity): List<TimeslotInfo> {
        val blocks = PeriodBlock.decodeList(run.periodBlocksEncoded).ifEmpty { PeriodBlock.FALLBACK_DEFAULT }
        val days = run.activeDaysEncoded.split(",").mapNotNull { it.trim().toIntOrNull() }.ifEmpty { PeriodBlock.FALLBACK_DEFAULT_DAYS }
        return TimeslotGenerator.generate(blocks, days)
    }

    /**
     * Generate New Schedule / Generate Examination Schedule / any other type-specific run.
     *
     * [sessionType] is mandatory and is ANDed into the session selection alongside the caller's own
     * [sessionFilter] — a run can never end up colored from a mix of e.g. CLASS and LAB sessions.
     *
     * [periodBlocks]/[activeDays] are THIS timetable's own periods, chosen moments earlier in the
     * creation wizard (pick type -> define periods -> generate) — not read from any shared setting.
     * That's what makes different timetables able to have different time periods, and it's also the
     * fix for the old "select more than one day -> blank schedule" bug: periods are computed once,
     * in memory, right here, in the same call that uses them, instead of being saved to a database
     * table and separately read back by a different code path moments later.
     */
    suspend fun generate(
        name: String,
        mode: String,
        sessionType: SessionTypeEntity,
        periodBlocks: List<PeriodBlock>,
        activeDays: List<Int>,
        algorithmName: String = ColoringAlgorithmRegistry.default.name,
        sessionFilter: (SessionEntity) -> Boolean = { true },
    ): String {
        val sortedDays = activeDays.sorted()
        val timeslots = TimeslotGenerator.generate(periodBlocks, sortedDays)
        val input = buildSchedulingInput(timeslots) { session -> session.type == sessionType && sessionFilter(session) }
        val algorithm = ColoringAlgorithmRegistry.algorithms[algorithmName] ?: ColoringAlgorithmRegistry.default
        val startTime = System.currentTimeMillis()
        val output = SchedulingEngine.generate(input, algorithm)
        val elapsed = System.currentTimeMillis() - startTime

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = name,
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = algorithm.name,
            mode = mode,
            executionTimeMillis = elapsed,
            sessionType = sessionType,
            periodBlocksEncoded = PeriodBlock.encodeList(periodBlocks),
            activeDaysEncoded = sortedDays.joinToString(","),
        )
        persistRun(run, output.assignments, output.roomBySession, output.violations)
        return runId
    }

    /** Validate Existing Schedule — re-checks a saved run's current assignments (against its OWN period blocks and only its own session type) and refreshes its conflict records. */
    suspend fun validate(runId: String): List<ConstraintViolation> {
        val run = database.scheduleRunDao().getById(runId) ?: return emptyList()
        val input = buildSchedulingInput(timeslotsFor(run)) { it.type == run.sessionType }
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(runId)
        val assignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()

        val violations = ConstraintValidator.validate(
            ValidationContext(
                sessions = input.sessions,
                assignments = assignments,
                roomBySession = roomBySession,
                rooms = input.rooms,
                sectionStudentCounts = input.sectionStudentCounts,
                blockedTeacherSlots = input.blockedTeacherSlots,
                blockedRoomSlots = input.blockedRoomSlots,
                definedPeriodsByDay = input.definedPeriodsByDay,
            ),
        )

        database.withTransaction {
            persistConflicts(runId, violations)
        }
        return violations
    }

    /**
     * The standalone Repair feature's entry point — a school uploads an assignments.csv describing
     * a schedule that ALREADY EXISTS (possibly with conflicts) rather than asking the engine to
     * generate one. [periodBlocks]/[activeDays] are the periods THIS uploaded schedule follows
     * (chosen via the same creation-wizard periods step Generate uses), stored on the run so
     * Validate/Optimize/Export against it use the right grid. This persists it as a new run exactly
     * as given (no coloring, no engine involvement at all) and then immediately calls [validate] on
     * it, so the returned violations are real and the run's conflict_records are already populated
     * the moment this returns.
     */
    suspend fun importExistingSchedule(
        name: String,
        sessionType: SessionTypeEntity,
        periodBlocks: List<PeriodBlock>,
        activeDays: List<Int>,
        rows: List<ScheduleAssignmentEntity>,
    ): Pair<String, List<ConstraintViolation>> {
        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = name,
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = "imported",
            mode = ScheduleMode.IMPORTED,
            executionTimeMillis = 0,
            sessionType = sessionType,
            periodBlocksEncoded = PeriodBlock.encodeList(periodBlocks),
            activeDaysEncoded = activeDays.sorted().joinToString(","),
        )
        val assignments = rows.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = rows.mapNotNull { r -> r.roomId?.let { r.sessionId to it } }.toMap()
        persistRun(run, assignments, roomBySession, emptyList())
        val violations = validate(runId)
        return runId to violations
    }

    /**
     * Repair Conflicting Schedule — produces a NEW schedule run (mode REPAIR) rather than mutating
     * the original. The new run inherits the source run's own period blocks/days and session type —
     * repairing a schedule never changes what periods or type it was built for, only which sessions
     * land where.
     */
    suspend fun repair(sourceRunId: String, algorithmName: String = ColoringAlgorithmRegistry.default.name): String {
        val sourceRun = database.scheduleRunDao().getById(sourceRunId)
        val input = buildSchedulingInput(sourceRun?.let(::timeslotsFor).orEmpty()) { it.type == (sourceRun?.sessionType ?: SessionTypeEntity.CLASS) }
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(sourceRunId)
        val existingAssignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val existingRoomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()
        val algorithm = ColoringAlgorithmRegistry.algorithms[algorithmName] ?: ColoringAlgorithmRegistry.default

        val startTime = System.currentTimeMillis()
        val result: RepairResult = RepairEngine.repair(input, existingAssignments, existingRoomBySession, algorithm)
        val elapsed = System.currentTimeMillis() - startTime

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = "${sourceRun?.name ?: "Schedule"} (repaired)",
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = algorithm.name,
            mode = ScheduleMode.REPAIR,
            executionTimeMillis = elapsed,
            sessionType = sourceRun?.sessionType ?: SessionTypeEntity.CLASS,
            periodBlocksEncoded = sourceRun?.periodBlocksEncoded.orEmpty(),
            activeDaysEncoded = sourceRun?.activeDaysEncoded.orEmpty(),
            // sourceRun's OWN rootRunId if it's already history, else sourceRun IS the root —
            // keeps every lineage flat at one level no matter how many repairs deep this is.
            rootRunId = sourceRun?.rootRunId ?: sourceRunId,
        )
        persistRun(run, result.assignments, result.roomBySession, result.remainingViolations)
        return runId
    }

    /** Optimize Existing Schedule — also produces a new run, same reasoning as repair(). */
    suspend fun optimize(sourceRunId: String, maxPasses: Int = 3): String {
        val sourceRun = database.scheduleRunDao().getById(sourceRunId)
        val input = buildSchedulingInput(sourceRun?.let(::timeslotsFor).orEmpty()) { it.type == (sourceRun?.sessionType ?: SessionTypeEntity.CLASS) }
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(sourceRunId)
        val assignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()
        val totalDefinedPeriods = input.definedPeriodsByDay.values.sumOf { it.size }

        val startTime = System.currentTimeMillis()
        val result: OptimizationResult = ScheduleOptimizer.optimize(
            input, assignments, roomBySession, input.rooms.size, totalDefinedPeriods, maxPasses,
        )
        val elapsed = System.currentTimeMillis() - startTime

        val violations = ConstraintValidator.validate(
            ValidationContext(
                sessions = input.sessions,
                assignments = result.assignments,
                roomBySession = result.roomBySession,
                rooms = input.rooms,
                sectionStudentCounts = input.sectionStudentCounts,
                blockedTeacherSlots = input.blockedTeacherSlots,
                blockedRoomSlots = input.blockedRoomSlots,
                definedPeriodsByDay = input.definedPeriodsByDay,
            ),
        )

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = "${sourceRun?.name ?: "Schedule"} (optimized)",
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = "optimize",
            mode = ScheduleMode.OPTIMIZE,
            executionTimeMillis = elapsed,
            sessionType = sourceRun?.sessionType ?: SessionTypeEntity.CLASS,
            periodBlocksEncoded = sourceRun?.periodBlocksEncoded.orEmpty(),
            activeDaysEncoded = sourceRun?.activeDaysEncoded.orEmpty(),
            rootRunId = sourceRun?.rootRunId ?: sourceRunId,
        )
        persistRun(run, result.assignments, result.roomBySession, violations)
        return runId
    }

    /** Home's list — one card per lineage. */
    suspend fun getRootRuns(): List<ScheduleRunEntity> = database.scheduleRunDao().getAllRoots()

    /** A lineage's full history (root + every repair/optimize on it), oldest first — what Timetable Detail scrolls through. */
    suspend fun getLineage(rootRunId: String): List<ScheduleRunEntity> = database.scheduleRunDao().getLineage(rootRunId)

    suspend fun getRuns(): List<ScheduleRunEntity> = database.scheduleRunDao().getAll()

    suspend fun getRun(runId: String): ScheduleRunEntity? = database.scheduleRunDao().getById(runId)

    /** A run's own period blocks, decoded — what Home/Timetable Detail display as "define time period" for that entry. */
    fun periodBlocksOf(run: ScheduleRunEntity): List<PeriodBlock> = PeriodBlock.decodeList(run.periodBlocksEncoded)

    fun activeDaysOf(run: ScheduleRunEntity): List<Int> = run.activeDaysEncoded.split(",").mapNotNull { it.trim().toIntOrNull() }

    /** runId -> conflict count, for every run that has at least one conflict. Missing from the map means clean. */
    suspend fun getConflictCountsByRun(): Map<String, Int> =
        database.scheduleRunDao().getConflictCountsByRun().associate { it.scheduleRunId to it.conflictCount }

    /**
     * Deletes a run and everything scoped to it (assignments, conflict records) — never touches
     * the shared teacher/subject/room/session data those assignments point at. If [runId] is a
     * lineage ROOT, every Validate/Repair/Optimize entry built on top of it is deleted too, so
     * "Delete Timetable" removes the whole history shown on the detail screen, not just the
     * original Generate run while its later entries silently orphan in the database.
     */
    suspend fun deleteRun(runId: String) {
        database.withTransaction {
            val children = database.scheduleRunDao().getLineage(runId).filter { it.id != runId }
            for (child in children) {
                database.scheduleRunDao().deleteAssignmentsFor(child.id)
                database.scheduleRunDao().deleteConflictsFor(child.id)
                database.scheduleRunDao().deleteRun(child.id)
            }
            database.scheduleRunDao().deleteAssignmentsFor(runId)
            database.scheduleRunDao().deleteConflictsFor(runId)
            database.scheduleRunDao().deleteRun(runId)
        }
    }

    suspend fun getTeachers(): List<com.jpagdi.cromascheduler.data.entity.TeacherEntity> = database.teacherDao().getAll()

    /** Whether Generate has anything to work with yet for [type] — GenerateScreen uses this to point someone at Import Data instead of letting them tap Generate against zero sessions. */
    suspend fun sessionCountFor(type: SessionTypeEntity): Int = database.sessionDao().getAll().count { it.type == type }

    data class HomeCounts(val teachers: Int, val subjects: Int, val rooms: Int, val sessions: Int)

    suspend fun getHomeCounts(): HomeCounts = HomeCounts(
        teachers = database.teacherDao().getAll().size,
        subjects = database.subjectDao().getAll().size,
        rooms = database.roomDao().getAll().size,
        sessions = database.sessionDao().getAll().size,
    )

    /** A teacher's currently blocked (unavailable) periods, for rendering the toggle grid. */
    suspend fun getTeacherBlockedSlots(teacherId: String): Set<Timeslot> =
        database.availabilityDao().getBlocksFor(AvailabilityEntityType.TEACHER, teacherId)
            .map { Timeslot(it.dayOfWeek, it.periodIndex) }
            .toSet()

    /** In-app equivalent of a row in availability.csv — lets a teacher mark/unmark a single period without a fresh CSV import. */
    suspend fun setTeacherBlocked(teacherId: String, day: Int, period: Int, blocked: Boolean) {
        if (blocked) {
            database.availabilityDao().upsert(
                com.jpagdi.cromascheduler.data.entity.AvailabilityBlockEntity(AvailabilityEntityType.TEACHER, teacherId, day, period),
            )
        } else {
            database.availabilityDao().deleteBlock(AvailabilityEntityType.TEACHER, teacherId, day, period)
        }
    }

    suspend fun getAssignments(runId: String): List<ScheduleAssignmentEntity> = database.scheduleRunDao().getAssignmentsFor(runId)

    suspend fun getConflicts(runId: String): List<ConflictRecordEntity> = database.scheduleRunDao().getConflictsFor(runId)

    /**
     * Joins a run's raw assignments against every name lookup (subject/teacher/
     * section/room/timeslot) needed for display. Shared by the Results screen and
     * every export format. Timeslot start/end times come from THIS run's own
     * period blocks, not a shared table.
     */
    suspend fun buildExportRows(runId: String): List<ScheduleExportRow> {
        val run = database.scheduleRunDao().getById(runId) ?: return emptyList()
        val assignments = database.scheduleRunDao().getAssignmentsFor(runId)
            .sortedWith(compareBy({ it.dayOfWeek }, { it.periodIndex }))
        val sessions = database.sessionDao().getAll().associateBy { it.id }
        val subjects = database.subjectDao().getAll().associateBy { it.id }
        val teachers = database.teacherDao().getAll().associateBy { it.id }
        val sections = database.sectionDao().getAll().associateBy { it.id }
        val rooms = database.roomDao().getAll().associateBy { it.id }
        val timeslots = timeslotsFor(run).associateBy { it.dayOfWeek to it.periodIndex }

        return assignments.mapNotNull { a ->
            val session = sessions[a.sessionId] ?: return@mapNotNull null
            val timeslot = timeslots[a.dayOfWeek to a.periodIndex]
            ScheduleExportRow(
                sessionId = session.id,
                sessionType = session.type.name,
                subjectName = session.subjectId?.let { subjects[it]?.name } ?: "—",
                teacherName = session.teacherId?.let { teachers[it]?.name } ?: "—",
                sectionName = session.sectionId?.let { sections[it]?.name } ?: "—",
                roomName = a.roomId?.let { rooms[it]?.name } ?: "Unassigned",
                dayLabel = DAY_NAMES[a.dayOfWeek] ?: "Day ${a.dayOfWeek}",
                startTime = timeslot?.startTime ?: "Period ${a.periodIndex}",
                endTime = timeslot?.endTime.orEmpty(),
            )
        }
    }

    companion object {
        // dayOfWeek follows java.time.DayOfWeek.getValue() convention: 1=Monday .. 7=Sunday.
        private val DAY_NAMES = mapOf(
            1 to "Monday", 2 to "Tuesday", 3 to "Wednesday", 4 to "Thursday",
            5 to "Friday", 6 to "Saturday", 7 to "Sunday",
        )
    }

    private suspend fun persistRun(
        run: ScheduleRunEntity,
        assignments: Map<String, Timeslot>,
        roomBySession: Map<String, String>,
        violations: List<ConstraintViolation>,
    ) {
        database.withTransaction {
            database.scheduleRunDao().upsert(run)
            val assignmentEntities = assignments.map { (sessionId, ts) ->
                ScheduleAssignmentEntity(run.id, sessionId, ts.dayOfWeek, ts.periodIndex, roomBySession[sessionId])
            }
            database.scheduleRunDao().upsertAssignments(assignmentEntities)
            persistConflicts(run.id, violations)
        }
    }

    private suspend fun persistConflicts(runId: String, violations: List<ConstraintViolation>) {
        val entities = violations.map {
            ConflictRecordEntity(
                scheduleRunId = runId,
                sessionAId = it.sessionAId,
                sessionBId = it.sessionBId,
                conflictType = it.type.name,
                reason = it.message,
            )
        }
        database.scheduleRunDao().upsertConflicts(entities)
    }
}
