package com.jpagdi.cromascheduler.data.repository

import androidx.room.withTransaction
import com.jpagdi.cromascheduler.data.db.CromaDatabase
import com.jpagdi.cromascheduler.data.entity.AvailabilityEntityType
import com.jpagdi.cromascheduler.data.entity.ConflictRecordEntity
import com.jpagdi.cromascheduler.data.entity.PeriodBlock
import com.jpagdi.cromascheduler.data.entity.ScheduleAssignmentEntity
import com.jpagdi.cromascheduler.data.entity.ScheduleRunEntity
import com.jpagdi.cromascheduler.data.entity.SessionEntity
import com.jpagdi.cromascheduler.data.entity.SessionTypeEntity
import com.jpagdi.cromascheduler.data.export.ScheduleExportRow
import com.jpagdi.cromascheduler.data.timeslot.TimeslotGenerator
import com.jpagdi.cromascheduler.data.timeslot.TimeslotInfo
import com.jpagdi.cromascheduler.engine.SchedulingEngine
import com.jpagdi.cromascheduler.engine.SchedulingInput
import com.jpagdi.cromascheduler.engine.coloring.ColoringAlgorithmRegistry
import com.jpagdi.cromascheduler.engine.model.Timeslot
import com.jpagdi.cromascheduler.engine.optimize.OptimizationResult
import com.jpagdi.cromascheduler.engine.optimize.ScheduleOptimizer
import com.jpagdi.cromascheduler.engine.repair.RepairEngine
import com.jpagdi.cromascheduler.engine.repair.RepairResult
import com.jpagdi.cromascheduler.engine.rooms.EngineRoom
import com.jpagdi.cromascheduler.engine.validation.ConstraintValidator
import com.jpagdi.cromascheduler.engine.validation.ConstraintViolation
import com.jpagdi.cromascheduler.engine.validation.ValidationContext
import java.util.UUID
import org.json.JSONArray
import org.json.JSONObject

object ScheduleMode {
    const val GENERATE = "GENERATE"
    const val GENERATE_EXAM = "GENERATE_EXAM"
    const val REPAIR = "REPAIR"
    const val OPTIMIZE = "OPTIMIZE"
    const val IMPORTED = "IMPORTED" // an existing schedule uploaded for the standalone Repair feature, not generated by the engine
}

/**
 * The single place that assembles a SchedulingInput from whatever's currently in
 * Room and turns engine output back into persisted rows. Every "mode" the spec
 * lists (Generate / Generate Exam / Validate / Repair / Optimize) goes through the
 * SAME underlying engine calls — the only thing that differs between them is which
 * sessions get selected and which engine entry point gets called.
 */
class ScheduleRepository(private val database: CromaDatabase) {


    /**
     * Snapshot of the current imported source dataset. A timetable keeps this copy so replacing
     * the working import for the next timetable never destroys the data needed to display,
     * validate, repair, optimize, or export an older timetable.
     */
    private data class SourceSnapshot(
        val teachers: List<com.jpagdi.cromascheduler.data.entity.TeacherEntity>,
        val subjects: List<com.jpagdi.cromascheduler.data.entity.SubjectEntity>,
        val rooms: List<com.jpagdi.cromascheduler.data.entity.RoomEntity>,
        val sections: List<com.jpagdi.cromascheduler.data.entity.SectionEntity>,
        val sessions: List<SessionEntity>,
        val availability: List<com.jpagdi.cromascheduler.data.entity.AvailabilityBlockEntity>,
    )

    private suspend fun captureSourceSnapshot(): String {
        val root = JSONObject()
        val teachers = database.teacherDao().getAll()
        val subjects = database.subjectDao().getAll()
        val rooms = database.roomDao().getAll()
        val sections = database.sectionDao().getAll()
        val sessions = database.sessionDao().getAll()
        val availability = database.availabilityDao().getAll()
        root.put("teachers", JSONArray().apply {
            teachers.forEach { t ->
                put(JSONObject().apply {
                    put("id", t.id); put("name", t.name); put("subjectIds", JSONArray(t.subjectIds))
                    t.maxLoadPerDay?.let { put("maxLoadPerDay", it) }
                })
            }
        })
        root.put("subjects", JSONArray().apply {
            subjects.forEach { v -> put(JSONObject().apply { put("id", v.id); put("name", v.name); put("code", v.code) }) }
        })
        root.put("rooms", JSONArray().apply {
            rooms.forEach { v -> put(JSONObject().apply { put("id", v.id); put("name", v.name); put("capacity", v.capacity); put("type", v.type) }) }
        })
        root.put("sections", JSONArray().apply {
            sections.forEach { v -> put(JSONObject().apply { put("id", v.id); put("name", v.name); put("studentCount", v.studentCount) }) }
        })
        root.put("sessions", JSONArray().apply {
            sessions.forEach { v ->
                put(JSONObject().apply {
                    put("id", v.id); put("type", v.type.name)
                    put("subjectId", v.subjectId); put("teacherId", v.teacherId); put("sectionId", v.sectionId)
                    put("roomTypeRequired", v.roomTypeRequired); put("durationPeriods", v.durationPeriods)
                })
            }
        })
        root.put("availability", JSONArray().apply {
            availability.forEach { v ->
                put(JSONObject().apply {
                    put("entityType", v.entityType.name); put("entityId", v.entityId)
                    put("dayOfWeek", v.dayOfWeek); put("periodIndex", v.periodIndex)
                })
            }
        })
        return root.toString()
    }

    private fun snapshotFrom(encoded: String): SourceSnapshot? {
        if (encoded.isBlank()) return null
        return runCatching {
            val root = JSONObject(encoded)
            fun array(name: String) = root.optJSONArray(name) ?: JSONArray()
            val teachers = buildList {
                val a = array("teachers")
                for (i in 0 until a.length()) {
                    val o = a.getJSONObject(i)
                    val ids = o.optJSONArray("subjectIds")
                    add(com.jpagdi.cromascheduler.data.entity.TeacherEntity(
                        id = o.getString("id"), name = o.getString("name"),
                        subjectIds = buildList { if (ids != null) for (j in 0 until ids.length()) add(ids.getString(j)) },
                        maxLoadPerDay = if (o.has("maxLoadPerDay")) o.optInt("maxLoadPerDay") else null,
                    ))
                }
            }
            val subjects = buildList {
                val a = array("subjects"); for (i in 0 until a.length()) { val o=a.getJSONObject(i); add(com.jpagdi.cromascheduler.data.entity.SubjectEntity(o.getString("id"),o.getString("name"),o.getString("code"))) }
            }
            val rooms = buildList {
                val a = array("rooms"); for (i in 0 until a.length()) { val o=a.getJSONObject(i); add(com.jpagdi.cromascheduler.data.entity.RoomEntity(o.getString("id"),o.getString("name"),o.getInt("capacity"),o.getString("type"))) }
            }
            val sections = buildList {
                val a = array("sections"); for (i in 0 until a.length()) { val o=a.getJSONObject(i); add(com.jpagdi.cromascheduler.data.entity.SectionEntity(o.getString("id"),o.getString("name"),o.getInt("studentCount"))) }
            }
            val sessions = buildList {
                val a = array("sessions"); for (i in 0 until a.length()) {
                    val o=a.getJSONObject(i)
                    add(SessionEntity(
                        id=o.getString("id"), type=SessionTypeEntity.valueOf(o.getString("type")),
                        subjectId=o.optString("subjectId", null), teacherId=o.optString("teacherId", null),
                        sectionId=o.optString("sectionId", null), roomTypeRequired=o.optString("roomTypeRequired", null),
                        durationPeriods=o.optInt("durationPeriods", 1),
                    ))
                }
            }
            val availability = buildList {
                val a = array("availability"); for (i in 0 until a.length()) {
                    val o=a.getJSONObject(i)
                    add(com.jpagdi.cromascheduler.data.entity.AvailabilityBlockEntity(
                        AvailabilityEntityType.valueOf(o.getString("entityType")), o.getString("entityId"),
                        o.getInt("dayOfWeek"), o.getInt("periodIndex"),
                    ))
                }
            }
            SourceSnapshot(teachers, subjects, rooms, sections, sessions, availability)
        }.getOrNull()
    }

    private suspend fun buildSchedulingInputForRun(run: ScheduleRunEntity): SchedulingInput {
        val snapshot = snapshotFrom(run.sourceSnapshotEncoded)
        return if (snapshot == null) {
            buildSchedulingInput(timeslotsFor(run)) { it.type == run.sessionType }
        } else {
            buildSchedulingInputFromSnapshot(timeslotsFor(run), snapshot, run.sessionType)
        }
    }

    private fun buildSchedulingInputFromSnapshot(
        timeslots: List<TimeslotInfo>,
        snapshot: SourceSnapshot,
        sessionType: SessionTypeEntity,
    ): SchedulingInput {
        val engineSessions = snapshot.sessions.filter { it.type == sessionType }.toEngineSessions()
        val engineRooms = snapshot.rooms.map { EngineRoom(it.id, it.capacity, it.type) }
        val sectionCounts = snapshot.sections.associate { it.id to it.studentCount }
        val blockedTeacher = snapshot.teachers.associate { teacher ->
            teacher.id to snapshot.availability.filter { it.entityType == AvailabilityEntityType.TEACHER && it.entityId == teacher.id }
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }.toSet()
        }
        val blockedRoom = snapshot.rooms.associate { room ->
            room.id to snapshot.availability.filter { it.entityType == AvailabilityEntityType.ROOM && it.entityId == room.id }
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }.toSet()
        }
        val allTimeslots = timeslots.map { Timeslot(it.dayOfWeek, it.periodIndex) }
        val definedPeriodsByDay = timeslots.groupBy { it.dayOfWeek }.mapValues { (_, v) -> v.map { it.periodIndex }.toSet() }
        val availableBySession = engineSessions.associate { session ->
            val blocked = session.teacherId?.let { blockedTeacher[it] }.orEmpty()
            session.id to allTimeslots.filter { it !in blocked }
        }
        return SchedulingInput(
            sessions = engineSessions,
            availableTimeslotsBySession = availableBySession,
            rooms = engineRooms,
            sectionStudentCounts = sectionCounts,
            blockedTeacherSlots = blockedTeacher,
            blockedRoomSlots = blockedRoom,
            definedPeriodsByDay = definedPeriodsByDay,
        )
    }

    /** [timeslots] is always supplied by the caller now — see [timeslotsFor], the one place that decides which run's period blocks apply. There's no global fallback here on purpose: a caller that forgets to pass real timeslots gets an empty, clearly-broken result, not a silently-wrong one borrowed from some other run. */
    suspend fun buildSchedulingInput(timeslots: List<TimeslotInfo>, sessionFilter: (SessionEntity) -> Boolean = { true }): SchedulingInput {
        val teachers = database.teacherDao().getAll()
        val rooms = database.roomDao().getAll()
        val sections = database.sectionDao().getAll()
        val sessions = database.sessionDao().getAll().filter(sessionFilter)

        val engineSessions = sessions.toEngineSessions()
        val engineRooms = rooms.map { EngineRoom(it.id, it.capacity, it.type) }
        val sectionCounts = sections.associate { it.id to it.studentCount }

        val blockedTeacher = teachers.associate { teacher ->
            teacher.id to database.availabilityDao()
                .getBlocksFor(AvailabilityEntityType.TEACHER, teacher.id)
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }
                .toSet()
        }
        val blockedRoom = rooms.associate { room ->
            room.id to database.availabilityDao()
                .getBlocksFor(AvailabilityEntityType.ROOM, room.id)
                .map { Timeslot(it.dayOfWeek, it.periodIndex) }
                .toSet()
        }

        val allTimeslots = timeslots.map { Timeslot(it.dayOfWeek, it.periodIndex) }
        val definedPeriodsByDay = timeslots.groupBy { it.dayOfWeek }.mapValues { (_, v) -> v.map { it.periodIndex }.toSet() }

        val availableBySession = engineSessions.associate { session ->
            val blocked = session.teacherId?.let { blockedTeacher[it] }.orEmpty()
            session.id to allTimeslots.filter { it !in blocked }
        }

        return SchedulingInput(
            sessions = engineSessions,
            availableTimeslotsBySession = availableBySession,
            rooms = engineRooms,
            sectionStudentCounts = sectionCounts,
            blockedTeacherSlots = blockedTeacher,
            blockedRoomSlots = blockedRoom,
            definedPeriodsByDay = definedPeriodsByDay,
        )
    }

    /**
     * Decodes a run's OWN stored period blocks/days and regenerates its timeslot grid on the
     * spot — this is what replaced reading one shared global `timeslots` table. A run created
     * before periodBlocksEncoded/activeDaysEncoded existed (empty strings) falls back to a
     * generic default rather than producing zero timeslots and silently unresolving everything.
     */
    private fun timeslotsFor(run: ScheduleRunEntity): List<TimeslotInfo> {
        val blocks = PeriodBlock.decodeList(run.periodBlocksEncoded).ifEmpty { PeriodBlock.FALLBACK_DEFAULT }
        val days = run.activeDaysEncoded.split(",").mapNotNull { it.trim().toIntOrNull() }.ifEmpty { PeriodBlock.FALLBACK_DEFAULT_DAYS }
        return TimeslotGenerator.generate(blocks, days)
    }

    /**
     * Generate New Schedule / Generate Examination Schedule / any other type-specific run.
     *
     * [sessionType] is mandatory and is ANDed into the session selection alongside the caller's own
     * [sessionFilter] — a run can never end up colored from a mix of e.g. CLASS and LAB sessions.
     *
     * [periodBlocks]/[activeDays] are THIS timetable's own periods, chosen moments earlier in the
     * creation wizard (pick type -> define periods -> generate) — not read from any shared setting.
     * That's what makes different timetables able to have different time periods, and it's also the
     * fix for the old "select more than one day -> blank schedule" bug: periods are computed once,
     * in memory, right here, in the same call that uses them, instead of being saved to a database
     * table and separately read back by a different code path moments later.
     */
    suspend fun generate(
        name: String,
        mode: String,
        sessionType: SessionTypeEntity,
        periodBlocks: List<PeriodBlock>,
        activeDays: List<Int>,
        algorithmName: String = ColoringAlgorithmRegistry.default.name,
        sessionFilter: (SessionEntity) -> Boolean = { true },
    ): String {
        val sortedDays = activeDays.sorted()
        val timeslots = TimeslotGenerator.generate(periodBlocks, sortedDays)
        val input = buildSchedulingInput(timeslots) { session -> session.type == sessionType && sessionFilter(session) }
        val algorithm = ColoringAlgorithmRegistry.algorithms[algorithmName] ?: ColoringAlgorithmRegistry.default
        val startTime = System.currentTimeMillis()
        val output = SchedulingEngine.generate(input, algorithm)
        val elapsed = System.currentTimeMillis() - startTime
        val sourceSnapshot = captureSourceSnapshot()

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = name,
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = algorithm.name,
            mode = mode,
            executionTimeMillis = elapsed,
            sessionType = sessionType,
            periodBlocksEncoded = PeriodBlock.encodeList(periodBlocks),
            activeDaysEncoded = sortedDays.joinToString(","),
            sourceSnapshotEncoded = sourceSnapshot,
        )
        persistRun(run, output.assignments, output.roomBySession, output.violations)
        return runId
    }

    /** Validate Existing Schedule — re-checks a saved run's current assignments (against its OWN period blocks and only its own session type) and refreshes its conflict records. */
    suspend fun validate(runId: String): List<ConstraintViolation> {
        val run = database.scheduleRunDao().getById(runId) ?: return emptyList()
        val input = buildSchedulingInputForRun(run)
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(runId)
        val assignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()

        val violations = ConstraintValidator.validate(
            ValidationContext(
                sessions = input.sessions,
                assignments = assignments,
                roomBySession = roomBySession,
                rooms = input.rooms,
                sectionStudentCounts = input.sectionStudentCounts,
                blockedTeacherSlots = input.blockedTeacherSlots,
                blockedRoomSlots = input.blockedRoomSlots,
                definedPeriodsByDay = input.definedPeriodsByDay,
            ),
        )

        database.withTransaction {
            persistConflicts(runId, violations)
        }
        return violations
    }

    /**
     * The standalone Repair feature's entry point — a school uploads an assignments.csv describing
     * a schedule that ALREADY EXISTS (possibly with conflicts) rather than asking the engine to
     * generate one. [periodBlocks]/[activeDays] are the periods THIS uploaded schedule follows
     * (chosen via the same creation-wizard periods step Generate uses), stored on the run so
     * Validate/Optimize/Export against it use the right grid. This persists it as a new run exactly
     * as given (no coloring, no engine involvement at all) and then immediately calls [validate] on
     * it, so the returned violations are real and the run's conflict_records are already populated
     * the moment this returns.
     */
    suspend fun importExistingSchedule(
        name: String,
        sessionType: SessionTypeEntity,
        periodBlocks: List<PeriodBlock>,
        activeDays: List<Int>,
        rows: List<ScheduleAssignmentEntity>,
    ): Pair<String, List<ConstraintViolation>> {
        val sourceSnapshot = captureSourceSnapshot()
        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = name,
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = "imported",
            mode = ScheduleMode.IMPORTED,
            executionTimeMillis = 0,
            sessionType = sessionType,
            periodBlocksEncoded = PeriodBlock.encodeList(periodBlocks),
            activeDaysEncoded = activeDays.sorted().joinToString(","),
            sourceSnapshotEncoded = sourceSnapshot,
        )
        val assignments = rows.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = rows.mapNotNull { r -> r.roomId?.let { r.sessionId to it } }.toMap()
        persistRun(run, assignments, roomBySession, emptyList())
        val violations = validate(runId)
        return runId to violations
    }

    /**
     * Repair Conflicting Schedule — produces a NEW schedule run (mode REPAIR) rather than mutating
     * the original. The new run inherits the source run's own period blocks/days and session type —
     * repairing a schedule never changes what periods or type it was built for, only which sessions
     * land where.
     */
    suspend fun repair(
        sourceRunId: String,
        algorithmName: String = ColoringAlgorithmRegistry.default.name,
        selectedSessionIds: Set<String>? = null,
    ): String {
        val sourceRun = database.scheduleRunDao().getById(sourceRunId)
        val input = if (sourceRun != null) {
            buildSchedulingInputForRun(sourceRun)
        } else {
            buildSchedulingInput(emptyList())
        }
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(sourceRunId)
        val existingAssignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val existingRoomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()
        val algorithm = ColoringAlgorithmRegistry.algorithms[algorithmName] ?: ColoringAlgorithmRegistry.default

        val startTime = System.currentTimeMillis()
        val result: RepairResult = RepairEngine.repair(
            input, existingAssignments, existingRoomBySession, algorithm, selectedSessionIds = selectedSessionIds,
        )
        val elapsed = System.currentTimeMillis() - startTime

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = "${sourceRun?.name ?: "Schedule"} (repaired)",
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = algorithm.name,
            mode = ScheduleMode.REPAIR,
            executionTimeMillis = elapsed,
            sessionType = sourceRun?.sessionType ?: SessionTypeEntity.CLASS,
            periodBlocksEncoded = sourceRun?.periodBlocksEncoded.orEmpty(),
            activeDaysEncoded = sourceRun?.activeDaysEncoded.orEmpty(),
            // sourceRun's OWN rootRunId if it's already history, else sourceRun IS the root —
            // keeps every lineage flat at one level no matter how many repairs deep this is.
            rootRunId = sourceRun?.rootRunId ?: sourceRunId,
            sourceSnapshotEncoded = sourceRun?.sourceSnapshotEncoded.orEmpty(),
        )
        persistRun(run, result.assignments, result.roomBySession, result.remainingViolations)
        return runId
    }

    data class OptimizationOutcome(
        val runId: String,
        val changes: Int,
        val swaps: Int,
        val violationsBefore: Int,
        val violationsAfter: Int,
        val beforeScore: Double,
        val afterScore: Double,
    )

    /** Optimize Existing Schedule — local repair first, quality improvement second.
     * The source run is never mutated; the result is a new version in the same lineage. */
    suspend fun optimize(sourceRunId: String, maxPasses: Int = 3, maxChanges: Int = 12): OptimizationOutcome {
        val sourceRun = database.scheduleRunDao().getById(sourceRunId)
        val input = if (sourceRun != null) {
            buildSchedulingInputForRun(sourceRun)
        } else {
            buildSchedulingInput(emptyList())
        }
        val savedAssignments = database.scheduleRunDao().getAssignmentsFor(sourceRunId)
        val assignments = savedAssignments.associate { it.sessionId to Timeslot(it.dayOfWeek, it.periodIndex) }
        val roomBySession = savedAssignments.mapNotNull { a -> a.roomId?.let { a.sessionId to it } }.toMap()
        val totalDefinedPeriods = input.definedPeriodsByDay.values.sumOf { it.size }
        val reportedViolations = validate(sourceRunId)
        val focusSessionIds = reportedViolations
            .flatMap { listOfNotNull(it.sessionAId, it.sessionBId) }
            .toSet()

        val startTime = System.currentTimeMillis()
        val result: OptimizationResult = ScheduleOptimizer.optimize(
            input, assignments, roomBySession, input.rooms.size, totalDefinedPeriods, maxPasses, maxChanges,
            focusSessionIds = focusSessionIds.ifEmpty { null },
        )
        val elapsed = System.currentTimeMillis() - startTime

        val violations = ConstraintValidator.validate(
            ValidationContext(
                sessions = input.sessions,
                assignments = result.assignments,
                roomBySession = result.roomBySession,
                rooms = input.rooms,
                sectionStudentCounts = input.sectionStudentCounts,
                blockedTeacherSlots = input.blockedTeacherSlots,
                blockedRoomSlots = input.blockedRoomSlots,
                definedPeriodsByDay = input.definedPeriodsByDay,
            ),
        )

        val runId = UUID.randomUUID().toString()
        val run = ScheduleRunEntity(
            id = runId,
            name = "${sourceRun?.name ?: "Schedule"} (optimized)",
            createdAtEpochMillis = System.currentTimeMillis(),
            algorithmUsed = "optimize",
            mode = ScheduleMode.OPTIMIZE,
            executionTimeMillis = elapsed,
            sessionType = sourceRun?.sessionType ?: SessionTypeEntity.CLASS,
            periodBlocksEncoded = sourceRun?.periodBlocksEncoded.orEmpty(),
            activeDaysEncoded = sourceRun?.activeDaysEncoded.orEmpty(),
            rootRunId = sourceRun?.rootRunId ?: sourceRunId,
            sourceSnapshotEncoded = sourceRun?.sourceSnapshotEncoded.orEmpty(),
        )
        persistRun(run, result.assignments, result.roomBySession, violations)
        return OptimizationOutcome(
            runId = runId,
            changes = result.changes.size,
            swaps = result.swaps,
            violationsBefore = result.violationsBefore,
            violationsAfter = result.violationsAfter,
            beforeScore = result.before.totalScore,
            afterScore = result.after.totalScore,
        )
    }

    /** Backfills source snapshots for pre-v1.0.1 runs while the current working dataset is still available. */
    suspend fun ensureLegacySnapshots() {
        val legacyRuns = database.scheduleRunDao().getAll().filter { it.sourceSnapshotEncoded.isBlank() }
        if (legacyRuns.isEmpty()) return
        val snapshot = captureSourceSnapshot()
        val hasCurrentData = database.sessionDao().getAll().isNotEmpty() ||
            database.teacherDao().getAll().isNotEmpty() ||
            database.subjectDao().getAll().isNotEmpty()
        if (!hasCurrentData) return
        database.withTransaction {
            legacyRuns.forEach { database.scheduleRunDao().upsert(it.copy(sourceSnapshotEncoded = snapshot)) }
        }
    }

    suspend fun renameRun(runId: String, rawName: String) {
        val sanitized = sanitizeRunName(rawName)
        database.scheduleRunDao().renameRun(runId, sanitized)
    }

    /** Home's list — one card per lineage. */
    suspend fun getRootRuns(): List<ScheduleRunEntity> = database.scheduleRunDao().getAllRoots()

    /** A lineage's full history (root + every repair/optimize on it), oldest first — what Timetable Detail scrolls through. */
    suspend fun getLineage(rootRunId: String): List<ScheduleRunEntity> = database.scheduleRunDao().getLineage(rootRunId)

    suspend fun getRuns(): List<ScheduleRunEntity> = database.scheduleRunDao().getAll()

    suspend fun getRun(runId: String): ScheduleRunEntity? = database.scheduleRunDao().getById(runId)

    /** A run's own period blocks, decoded — what Home/Timetable Detail display as "define time period" for that entry. */
    fun periodBlocksOf(run: ScheduleRunEntity): List<PeriodBlock> = PeriodBlock.decodeList(run.periodBlocksEncoded)

    fun activeDaysOf(run: ScheduleRunEntity): List<Int> = run.activeDaysEncoded.split(",").mapNotNull { it.trim().toIntOrNull() }

    /** runId -> conflict count, for every run that has at least one conflict. Missing from the map means clean. */
    suspend fun getConflictCountsByRun(): Map<String, Int> =
        database.scheduleRunDao().getConflictCountsByRun().associate { it.scheduleRunId to it.conflictCount }

    /**
     * Deletes a run and everything scoped to it (assignments, conflict records) — never touches
     * the shared teacher/subject/room/session data those assignments point at. If [runId] is a
     * lineage ROOT, every Validate/Repair/Optimize entry built on top of it is deleted too, so
     * "Delete Timetable" removes the whole history shown on the detail screen, not just the
     * original Generate run while its later entries silently orphan in the database.
     */
    suspend fun deleteRun(runId: String) {
        database.withTransaction {
            val children = database.scheduleRunDao().getLineage(runId).filter { it.id != runId }
            for (child in children) {
                database.scheduleRunDao().deleteAssignmentsFor(child.id)
                database.scheduleRunDao().deleteConflictsFor(child.id)
                database.scheduleRunDao().deleteRun(child.id)
            }
            database.scheduleRunDao().deleteAssignmentsFor(runId)
            database.scheduleRunDao().deleteConflictsFor(runId)
            database.scheduleRunDao().deleteRun(runId)
        }
    }

    /**
     * Deletes exactly one version from a lineage's timeline, and only that one. If [runId] is
     * the lineage ROOT and other versions (Validate/Repair/Optimize entries) still exist under
     * it, the root's own data is removed but the lineage survives: the oldest remaining version
     * is promoted to be the new root (its rootRunId cleared) and every other sibling is
     * re-pointed at that new root's id, so Home keeps showing one card for the lineage. Deleting
     * the root only takes the whole timetable down with it when it was the last version left —
     * "as long as there's an active version, the timetable exists."
     *
     * Returns the id that now identifies this lineage's root (unchanged if a non-root version
     * was deleted, the newly-promoted root's id if the root was deleted with survivors, or null
     * if the whole lineage is now gone).
     */
    suspend fun deleteVersion(runId: String): String? {
        return database.withTransaction {
            val run = database.scheduleRunDao().getById(runId) ?: return@withTransaction null
            val isRoot = run.rootRunId == null
            val resultRootId: String? = if (isRoot) {
                val siblings = database.scheduleRunDao().getLineage(runId).filter { it.id != runId }
                if (siblings.isNotEmpty()) {
                    val newRoot = siblings.minByOrNull { it.createdAtEpochMillis }!!
                    database.scheduleRunDao().upsert(newRoot.copy(rootRunId = null))
                    for (sibling in siblings) {
                        if (sibling.id == newRoot.id) continue
                        database.scheduleRunDao().upsert(sibling.copy(rootRunId = newRoot.id))
                    }
                    newRoot.id
                } else {
                    null
                }
            } else {
                run.rootRunId
            }
            database.scheduleRunDao().deleteAssignmentsFor(runId)
            database.scheduleRunDao().deleteConflictsFor(runId)
            database.scheduleRunDao().deleteRun(runId)
            resultRootId
        }
    }

    suspend fun getTeachers(): List<com.jpagdi.cromascheduler.data.entity.TeacherEntity> = database.teacherDao().getAll()

    /** Whether Generate has anything to work with yet for [type] — GenerateScreen uses this to point someone at Import Data instead of letting them tap Generate against zero sessions. */
    suspend fun sessionCountFor(type: SessionTypeEntity): Int = database.sessionDao().getAll().count { it.type == type }

    data class HomeCounts(val teachers: Int, val subjects: Int, val rooms: Int, val sessions: Int)

    /** Clears only the current working import. Saved timetable runs remain intact because each run stores its own source snapshot. */
    suspend fun clearCurrentImportedData() {
        database.withTransaction {
            database.availabilityDao().clear()
            database.sessionDao().clear()
            database.sectionDao().clear()
            database.roomDao().clear()
            database.subjectDao().clear()
            database.teacherDao().clear()
        }
    }

    suspend fun roomCountForRun(runId: String): Int {
        val run = database.scheduleRunDao().getById(runId) ?: return 0
        return snapshotFrom(run.sourceSnapshotEncoded)?.rooms?.size ?: database.roomDao().getAll().size
    }

    suspend fun getHomeCounts(): HomeCounts = HomeCounts(
        teachers = database.teacherDao().getAll().size,
        subjects = database.subjectDao().getAll().size,
        rooms = database.roomDao().getAll().size,
        sessions = database.sessionDao().getAll().size,
    )

    /** A teacher's currently blocked (unavailable) periods, for rendering the toggle grid. */
    suspend fun getTeacherBlockedSlots(teacherId: String): Set<Timeslot> =
        database.availabilityDao().getBlocksFor(AvailabilityEntityType.TEACHER, teacherId)
            .map { Timeslot(it.dayOfWeek, it.periodIndex) }
            .toSet()


    private suspend fun refreshTeacherAvailabilityInSnapshots(teacherId: String) {
        val blocks = database.availabilityDao().getBlocksFor(AvailabilityEntityType.TEACHER, teacherId)
        database.scheduleRunDao().getAll().forEach { run ->
            if (run.sourceSnapshotEncoded.isBlank()) return@forEach
            val root = runCatching { JSONObject(run.sourceSnapshotEncoded) }.getOrNull() ?: return@forEach
            val availability = root.optJSONArray("availability") ?: JSONArray()
            val retained = JSONArray()
            for (i in 0 until availability.length()) {
                val o = availability.getJSONObject(i)
                if (!(o.optString("entityType") == AvailabilityEntityType.TEACHER.name && o.optString("entityId") == teacherId)) {
                    retained.put(o)
                }
            }
            blocks.forEach {
                retained.put(JSONObject().apply {
                    put("entityType", AvailabilityEntityType.TEACHER.name)
                    put("entityId", teacherId)
                    put("dayOfWeek", it.dayOfWeek)
                    put("periodIndex", it.periodIndex)
                })
            }
            root.put("availability", retained)
            database.scheduleRunDao().upsert(run.copy(sourceSnapshotEncoded = root.toString()))
        }
    }

    /** In-app equivalent of a row in availability.csv — lets a teacher mark/unmark a single period without a fresh CSV import. */
    suspend fun setTeacherBlocked(teacherId: String, day: Int, period: Int, blocked: Boolean) {
        if (blocked) {
            database.availabilityDao().upsert(
                com.jpagdi.cromascheduler.data.entity.AvailabilityBlockEntity(AvailabilityEntityType.TEACHER, teacherId, day, period),
            )
        } else {
            database.availabilityDao().deleteBlock(AvailabilityEntityType.TEACHER, teacherId, day, period)
        }
        refreshTeacherAvailabilityInSnapshots(teacherId)
    }

    suspend fun getAssignments(runId: String): List<ScheduleAssignmentEntity> = database.scheduleRunDao().getAssignmentsFor(runId)

    suspend fun getConflicts(runId: String): List<ConflictRecordEntity> = database.scheduleRunDao().getConflictsFor(runId)

    /**
     * Joins a run's raw assignments against every name lookup (subject/teacher/
     * section/room/timeslot) needed for display. Shared by the Results screen and
     * every export format. Timeslot start/end times come from THIS run's own
     * period blocks, not a shared table.
     */
    suspend fun buildExportRows(runId: String): List<ScheduleExportRow> {
        val run = database.scheduleRunDao().getById(runId) ?: return emptyList()
        val assignments = database.scheduleRunDao().getAssignmentsFor(runId)
            .sortedWith(compareBy({ it.dayOfWeek }, { it.periodIndex }))
        val snapshot = snapshotFrom(run.sourceSnapshotEncoded)
        val sessions = (snapshot?.sessions ?: database.sessionDao().getAll()).associateBy { it.id }
        val subjects = (snapshot?.subjects ?: database.subjectDao().getAll()).associateBy { it.id }
        val teachers = (snapshot?.teachers ?: database.teacherDao().getAll()).associateBy { it.id }
        val sections = (snapshot?.sections ?: database.sectionDao().getAll()).associateBy { it.id }
        val rooms = (snapshot?.rooms ?: database.roomDao().getAll()).associateBy { it.id }
        val timeslots = timeslotsFor(run).associateBy { it.dayOfWeek to it.periodIndex }

        return assignments.mapNotNull { a ->
            val session = sessions[a.sessionId] ?: return@mapNotNull null
            val timeslot = timeslots[a.dayOfWeek to a.periodIndex]
            ScheduleExportRow(
                sessionId = session.id,
                sessionType = session.type.name,
                subjectName = session.subjectId?.let { subjects[it]?.name } ?: "—",
                teacherName = session.teacherId?.let { teachers[it]?.name } ?: "—",
                sectionName = session.sectionId?.let { sections[it]?.name } ?: "—",
                roomName = a.roomId?.let { rooms[it]?.name } ?: "Unassigned",
                dayLabel = DAY_NAMES[a.dayOfWeek] ?: "Day ${a.dayOfWeek}",
                startTime = timeslot?.startTime ?: "Period ${a.periodIndex}",
                endTime = timeslot?.endTime.orEmpty(),
            )
        }
    }

    /**
     * One side of a conflict, resolved to display names — what the guided Repair dialog groups
     * by (teacher/room/class/subject), instead of showing raw session ids or one flat message.
     */
    data class ConflictParticipant(
        val sessionId: String,
        val teacherId: String?,
        val teacherName: String?,
        val roomId: String?,
        val roomName: String?,
        val sectionId: String?,
        val sectionName: String?,
        val subjectId: String?,
        val subjectName: String?,
    )

    data class ConflictDetail(
        val id: Long,
        val conflictType: String,
        val reason: String,
        val sessionA: ConflictParticipant,
        val sessionB: ConflictParticipant?,
    )

    /**
     * [runId]'s conflicts joined with each side's teacher/room/class/subject names. Powers the
     * guided Repair flow: pick an entity kind (teacher/room/class/subject) -> pick which specific
     * ones are affected -> pick which conflict kind on their schedule to fix (time/room/class/
     * subject) -> repair only the sessions behind that exact selection.
     */
    suspend fun getConflictDetails(runId: String): List<ConflictDetail> {
        val run = database.scheduleRunDao().getById(runId) ?: return emptyList()
        val conflicts = database.scheduleRunDao().getConflictsFor(runId)
        if (conflicts.isEmpty()) return emptyList()
        val assignments = database.scheduleRunDao().getAssignmentsFor(runId).associateBy { it.sessionId }
        val snapshot = snapshotFrom(run.sourceSnapshotEncoded)
        val sessions = (snapshot?.sessions ?: database.sessionDao().getAll()).associateBy { it.id }
        val subjects = (snapshot?.subjects ?: database.subjectDao().getAll()).associateBy { it.id }
        val teachers = (snapshot?.teachers ?: database.teacherDao().getAll()).associateBy { it.id }
        val sections = (snapshot?.sections ?: database.sectionDao().getAll()).associateBy { it.id }
        val rooms = (snapshot?.rooms ?: database.roomDao().getAll()).associateBy { it.id }

        fun participant(sessionId: String): ConflictParticipant {
            val session = sessions[sessionId]
            val roomId = assignments[sessionId]?.roomId
            return ConflictParticipant(
                sessionId = sessionId,
                teacherId = session?.teacherId,
                teacherName = session?.teacherId?.let { teachers[it]?.name },
                roomId = roomId,
                roomName = roomId?.let { rooms[it]?.name },
                sectionId = session?.sectionId,
                sectionName = session?.sectionId?.let { sections[it]?.name },
                subjectId = session?.subjectId,
                subjectName = session?.subjectId?.let { subjects[it]?.name },
            )
        }

        return conflicts.map { c ->
            ConflictDetail(
                id = c.id,
                conflictType = c.conflictType,
                reason = c.reason,
                sessionA = participant(c.sessionAId),
                sessionB = c.sessionBId?.let { participant(it) },
            )
        }
    }

    companion object {
        fun sanitizeRunName(rawName: String): String {
            val trimmed = rawName.trim()
            return trimmed.ifBlank { "Untitled Timetable" }
        }

        // dayOfWeek follows java.time.DayOfWeek.getValue() convention: 1=Monday .. 7=Sunday.
        private val DAY_NAMES = mapOf(
            1 to "Monday", 2 to "Tuesday", 3 to "Wednesday", 4 to "Thursday",
            5 to "Friday", 6 to "Saturday", 7 to "Sunday",
        )
    }

    private suspend fun persistRun(
        run: ScheduleRunEntity,
        assignments: Map<String, Timeslot>,
        roomBySession: Map<String, String>,
        violations: List<ConstraintViolation>,
    ) {
        database.withTransaction {
            database.scheduleRunDao().upsert(run)
            val assignmentEntities = assignments.map { (sessionId, ts) ->
                ScheduleAssignmentEntity(run.id, sessionId, ts.dayOfWeek, ts.periodIndex, roomBySession[sessionId])
            }
            database.scheduleRunDao().upsertAssignments(assignmentEntities)
            persistConflicts(run.id, violations)
        }
    }

    private suspend fun persistConflicts(runId: String, violations: List<ConstraintViolation>) {
        database.scheduleRunDao().deleteConflictsFor(runId)
        val entities = violations.map {
            ConflictRecordEntity(
                scheduleRunId = runId,
                sessionAId = it.sessionAId,
                sessionBId = it.sessionBId,
                conflictType = it.type.name,
                reason = it.message,
            )
        }
        database.scheduleRunDao().upsertConflicts(entities)
    }
}
